#!/bin/sh
### BEGIN INIT INFO
# Provides:          PiServer Jar Service
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Launches the PiServer jar
### END INIT INFO
SERVICE_NAME=pi-server
PATH_TO_JAR="/usr/local/bin/PiServer.jar"
INIT_LOCATION="/usr/local/bin/INIT_FILE"
PID_PATH_NAME="/tmp/PiServer-pid"
timestamp=`date +%F.%H.%M.%S`
monitorName=pi-server-jar.$timestamp

. /lib/lsb/init-functions

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            java -jar $PATH_TO_JAR $INIT_LOCATION > /tmp/$monitorName 2>&1 &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            $LAUNCH_COMMAND &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    status)
    	status_of_proc -p $PID_PATH_NAME $PATH_TO_JAR $SERVICE_NAME && exit 0 || exit $?
    ;;
esac 
