#!/bin/sh
### BEGIN INIT INFO
# Provides:          Apk Reporter Service
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Apk Reporter service updates board_database with apks found
### END INIT INFO
SERVICE_NAME=apk-reporter
INIT_LOCATION="/usr/local/bin/apk-reporter.sh"
PID_PATH_NAME="/tmp/$SERVICE_NAME-pid"
timestamp=`date +%F.%H.%M.%S`
monitorName="$SERVICE_NAME.$timestamp"

. /lib/lsb/init-functions

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            ${INIT_LOCATION} &
  	    echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            start
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    status)
    	status_of_proc -p $PID_PATH_NAME $INIT_LOCATION $SERVICE_NAME && exit 0 || exit $?
    ;;
esac 
